---
title: "Proposal Draft 3"
author: "Max Brubaker"
date: "12/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction Paragraph: (research objective)


Current unknowns and controversies in the literature (Ex: @Luyssaert_2008 --> @Gundersen_2021 --> @Luyssaert_2021) regarding old growth forests demand a more collective understanding of the function and fate of these systems. We believe it is the misrepresentation of the below ground community significantly contributing to not only such contrasting findings, but also to the lack of clarity in soil science and soil ecosystem functionality as a whole. 

The general aim of this study is to analyze soil systems in terms of carbon functionality as successional stages (SS) progress. We want to see, given different levels of disturbance, if soil carbon functionality changes with time and community composition. To do this we have selected old growth forests as our study system due to the few available areas with remaining longevity, and fungi as our model organism as they are the stewards of soil carbon dynamics. In order to achieve our aims, the study will be broken down into three parts: Part 1 consists of a proof of concept experiment that will allow us to determine the impact of analyzing a fungal community through three different genome analysis methods. We will test the capability of amplicon sequencing, whole genome sequencing, and whole transcriptome sequencing in analyzing fungal communities among three different experiments. These experiments will test the influence of carbon-substrate type, soil type, and the level of microbial interference on the ability of these methods to accurately represent the given microbial community. These tests will be conducted on a known community consisting of 9 different saprotrophic fungi, containing (3) early, (3) middle, and (3) late succesional stage species. The results from Part 1 will dictate the methods used to analyze fungal communities in soil samples from the field. Part 2 will involve soil sampling and physiological measurements in attempts to capture any mechanisms or parameters associated with changes in fungal community as succession progresses. Part 3 will involve a greenhouse experiment taking soil samples from different SS's and testing carbon attributes such as enzymatic production, respiration rates (flux), and fractionation of carbon pools. This will allow us to further analyze functional differences among soils from varying SS's. Pending the results from Parts 1-3, we hope to repeat these methods in search for trends among different types old growth forests. The overall gap this research aims to fill is whether or not there are distinct soil functional differences based on carbon mechanisms provided by fungal community in forest succession. Providing insight to this gap will result in a number of opportunities for future research. This project appears to be the first to attempt to specifically determine if there are functional differences among soils along a forest succesional gradient. While we are only analyzing carbon and fungal communities, if trends arise, it opens a massive area of research in learning how soils differ functionally among different microbial communities in different systems (i.e. old growth vs managed). Alternatively, if no trends are observed and the null hypothesis is supported, it can provide reason for future researchers to save significant amounts of time and money on genomic analysis. These old growth ecosystems are natures natural responders to disturbances such as climate change. If they are able to adapt and respond to such changes, we can learn from them and they may provide answers to how we can move forward and look towards natural approaches to save our ever fleeting fertile soils.



This study aims to determine how soil fungal communities differ among forest sucessional stages (SS’s) in community structure and carbon functionality. Emerging research suggests that increase in forest SS may be associated with a number of below-ground processes. For example, it is evident that microbial community composition responds to forest SS development. As forest age increases, we see a shift from predominately r-strategic community (variable environment dominated by bacteria) to a community dominated by k-strategists (“stable” environment dominated by fungi [@Sun_2021, @Yan_2020, @McGee_2019, @Zhou_2017, and @Zhou_2017b]. Additionaly, increase in SS has been accompanied by an increase in microbial biomass (@Zhong_2018 and @Yan_2020). Contrarily, we see reductions in both microbial biomass and diversity when forests are reverted to stand initiation stages (@Rodriguez_Ramos_2020 and @Zhong_2018), with variation depending on disturbance type. It is clear in the literature that both physical and chemical disturbance can lead to substantial changes in the microbial community. Fungi have been chosen as our model organism to analyze soil microbial community and functionality. A number of studies have analyzed fungal community composition in search of “who is there” (metagenomics and whole genomic sequencing) but far less have looked into soil functionality through fungal community analysis in terms of “what are they doing” (metatranscriptomics and gene regulation). However, there is evidence suggesting a positive correlation between soil microbial diversity and soil ecosystem functionality (@Delgado_Baquerizo_2016). Understanding the link between soil conditions, microbial community composition, and forest functionality, is crucial for future forest management and preservation. An objective of this project is to test the ability of different genomic community analysis methods to provide information regarding a soil microbial community. We are aware that a experiment such as this could easily take up the entirety of a Ph.D. and that environmental sample are notoriously difficult to accurately measure in terms of genomics. We will maintain simplicity and analyze inoculated soils with known microbial communities to test the ability of certain methods (whole genome sequencing, metagenomics, and metatranscriptomics) in providing accurate representations of said community. The results from this experiment will dictate our future community analysis methods. This project will analyze forest systems in attempts to determine how successional stage is related to fungal community composition and how the resulting composition impacts the soil carbon functionality. We hope that this may provide new insights to forest functionality and new considerations when weighing ecosystem services





# Parabraph 2: 

Next I was debating a brief paragraph discussing fungi and their role in soils/forest systems, not sure if that’s logical or relevant enough.''






# Paragraph 3: 

Understanding the impact microbial community has on ecosystem functionality as forests succeed, and how the resulting soil characteristics respond, can greatly improve our ability to infer how forest ecosystems are influenced by environmental change. The findings of @Delgado_Baquerizo_2016 suggest ecosystem functionality is dependent on specific microbial diversity and that a shift in said diversity is likely to change the functionality and resulting ecosystem previsions/services. It is now apparent that as forest systems transition into later successional stages, we see a major change in microbial ecosystem diversity and composition(@Yan_2020 and @Zhou_2017). These, among other studies (@Sun_2021 and @Zhou_2017b), show that as forests age we see a shift from an r-dominated to a K-dominated microbial community. This is important as it not only shows that as forests age we shift into a fungal dominated soil ecosystem, but it also suggests that fungi are associated with forest ecosystem “stability” (see r/k-strategists for details). Furthermore, we see (@Jiang_2021) that the relative abundance of certain fungal communities significantly increase with succession. Conversely, it has been shown that bacterial groups decline or remain relatively unchanged along successional gradients (@Zhou_2017b and @Yan_2020). This suggests that fungi may become more involved in nutrient cycling as forest ages increase, or that bacteria are able to maintain functionality in different soil and environmental conditions. Understanding which organisms are present in soil systems is extremely important and there is a substantial amount of research present in the literature eluding to how microbial community composition changes among kingdoms (bacteria, fungi, etc) as forest age. Digging deeper, a majority of fungal community analysis revolves around genomic sequencing in search of the presence or absence within specific hierarchical classifications (i.e. phylum, class, genus, etc). However, this leaves us with massive oversight as to how these changes in community impact the corresponding ecosystem functionality.

I could then transition into dicussion about microbial (fungal genomics) or maybe move into Paragraph 4


# Paragraph 4:

Understanding how functionality and microbial community change over time is crucial however, natural undisturbed succession is becoming increasingly rare by the day. Ecosystem disturbance is happening more frequently via both natural (extreme weather) and anthropogenic (logging/management) means. 
-	info on how disturbance influences microbial community
-	type of disturbance may impact how the microbial community changes 
-	more..

    
# Paragraph 5: 

Maybe talk about parameters that have been shown to change as successional stages increase?


# Paragraph 6:

The last paragraph could touch on the lack of clarity in old growth analysis and how current decisions, controversies, etc do not even consider belowground community impact and that forest functionality may change with age/lack of disturbance?













