---
title: "What is my paper about"
author: "Max Brubaker"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a document in which I can try to develop my story as I move forward. It will also serve to help me stay on track and make sure my thoughts are clear and concise.

__The main gap__ that I am trying to fill is the idea that we do not fully understand how these different forest life stages differ in terms of their functionality. We continue to analyze how microbial communities differ in different biomes and forests as age goes on but we don't have a measurement of how that change in community changes how the forest functions. 
    + maybe it doesnt? Maybe function remains but that would indicate that the community like changed to allow certain microbes to be dominant and thrive in new conditions. 
    + We know that forests change in terms of soil properties, vegitation diversity, and to some extent ecosystem function as they age ~ but for some reason we seem to just assume that all of these different successional stages function the same. 
      - if this is the case, fine, then we need to understand how these new micriobial communities are able to maintain function while so many other parameters are changing. 
      - if this is NOT the case then we need to undertand how forest age changes functionality (fungi/carbon in our case)
      
__Additional gap__ that needs to be filled is this lack of clarity in old growth forests. From definitions to weather or not they are carbon sources/sinks. We need to know the answeres to these questions in order to properly assess them and make decisions in legislature. 
    + how can we argue weather or not an OGF is a carbon source or sink without even understanding how the soil systems differ in functionality?
    



#Missing:
  + a connection to carbon... this is a substantial portion
  
  
  





# Update 12/20/21:

Lets just put the idea of this thesis into a paragraph and work from there:


The goal of my thesis, as it currently stands, is to "get at" soil functionality in terms of soil age. So...does the functionality of soils change with the lack of disturbance? To do this, we decided to look at forest systems as they are some of the few systems that are still allowed to age and develop into these old growth stages. We then decided to measure soil functionality based on fungi because we want to analyze these soil systems in terms of carbon, and fungi are our stewards of soil carbon mechanism. So soils in forests, their fungal community composition, and the corresponding carbon functionality. Obviously this will be parred with as many physiological parameters as we can imagine that are useful for this. 

So the gap we are aiming to fill is __"Are there distinct soil functional differences based on carbon mechanisms provided by fungal community succession"__. And if so, are there specific communities common among old soils that allow for such functional differences.
  + Why is this important? 
    ++ For one I am hoping that this will provide reason for us to stop decimating Old Growth Systems... maybe if the people think that we can benefit from these organisms found in old systems we will preserve them and try to understand them better. 
    ++ If we find that these soils/communities are functionally different then it provokes so much further research.
        +++ It would demand us to not only look into the specifics of the fungal communities that are functionally different but it also would demand other researchers to look into other microbial communities from this approach.
        +++ If these communities offer functional differences we can figure out why, and start exploring using NATURAL fungal communities to improve soil carbon dynamics in areas that are barren. These OGF could litteraly act as a bank of natural responses to environmental conditions. 
        
        
So how will we accomplish this? The project will be broken into four main portions with the last portion being dependent on results from the first three.

### Part 1: Genomic expirement "forced fungal succession"
This experiment will serve as our way of verifying/testing the avaliable techniques for soil fungal community analysis. This is a microcosm proof of concept experiment that will allow us to determine the validity of analyzing a fungal community through three different methods
  + Amplicon sequencing: (18S primers in search of who is there in the fungal community)
  + Whole genome sequencing: (Shotgun for ALL genes present in the sample)
  + Whole transcriptome sequencing (WHAT genes are actively transcribed ~ active in the community)
  
We will test the ability of these methods analyze 9 fungal species (separated by early, middle, and late succession saprobes) over three different experiments. The goal of these experiments is to determine under what conditions are these analysis limited or what conditions are they successful. The result of these three experiments will determine which analytical method is used for genomic sequencing in this project. 
T1 will be an test of carbon substrate manipulation to see if the type of carbon source influences the three methods' ability to analyze who is there, what genes are there, and what genes are active. The idea here is that with different carbon sources (glucose, x, and lignin), we should see different gene expression, but the community composition and total gene profile should remain the same. T2 will test the influence of soil type and T3 will test the influence of microbial interference in attempts to simulate levels of environmental samples.



### Part 2: Feild expirement (sampling)
The second part of this thesis will involve field sampling. Here we will obtain soil samples for genomic sequencing as well as any and all physiological parameters that may influence fungal community and carbon functionality. Experimental design will simulate that of (@Trofymow...) where a chronosquence has been established and sampled since 1987. These chronosequence sites will serve as our first two old growth forests for soil analysis. 



### Part 3: Common garden expirement "greenhouse"
The final part of our experiment will take place shortly after field sampling is conducted. The purpose is to compare carbon functionality of soils from different successional stages in each forest. Soils will be tested for enzymatic production, respiration rates (flux), and fractionation of carbon pools. This will add to our knowledge of how soils from different SS differ in terms of functionality, if they do at all.




    

    
    

  