---
title: "Writting Notes (Miranda)"
author: "Max Brubaker"
date: "12/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# General: 

Your paper must flow logically, and any information that does not support your ideas or argument, get rid of it. Order is important

__Each paragraph should be a stand alone essay and have 1 stand alone idea__. This paragraph should have an introductory sentence that links it to story or the prior paragraph. 2-3 supporting sentences. 1-2 conclusion. (microcosm of essay)

ONE IDEA PER PARAGRAPH

Order: give each paragraph a subheading that tells me what that paragraph is about. 



# Introduction: *opportunity to frame your story* (1-3 pages)

what is your question, by the end of the first paragraph readers should know what your question is and why it is important.
Very important to stick to the point and focus on the topic.
Why are we asking the question and what is the gap we are trying to fill.



Once you are finished with the first paragraph. The remaining paragraphs should act as stand alone essays.

By the end of the introduction the readers should have JUST ENOUGH informaion of why this is an important question to answer and the general context.
  non scientist should be able to read this and understand.
  

#Body (subheadings suggested). 

This is where you provide evidence to answer our question. 

Each paragraph should build on the previous. If the paragraph is not important for the overall story, why is it there?
- summary sentence can be used to help with this.


#Conclusion: 

did we answer our question? What else do we need to know... etc. 
  
  















